import Head from 'next/head'
import Header from '../components/header/Header'
import Results from '../components/results/Results'
import Blogs from '../components/blog/Blogs'
import Partners from '../components/partners/Partners'

// import Image from 'next/image'
import homeStyle from '../styles/Home.module.scss'

//--- db ---
import db from '../data/db'


export default function Home() {

  return (
    <div className={homeStyle.home}>
      <Head>
        <title>mypass | Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* HEADER */}
      <Header db={db} />

      {/* RESULTS */}
      <Results label='Vos Evènements' db={db} />

      {/* BLOG */}
      <Blogs articles={db.articles} />

      {/* PARTNERS */}
      <Partners partners={db.partners} />

      {/* <main className={homeStyle.main}></main> */}

      <footer className={homeStyle.footer}>
          <p className={homeStyle.text}>mypass <span>&copy;{`2021`}</span> tous droits réservés</p>
      </footer>
    </div>
  )
}
